server:
  port: 8085

logging:
  level:
    root: info
    com.status.backend: debug

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://k5a101.p.ssafy.io:3306/데이터배이스 이름
#    username: dawit
#    password: free101#

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    showSql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties.hibernate:
#      hbm2ddl.auto: update
      format_sql: true


