server:
  port: 8085

logging:
  level:
    root: info
    com.status.backend: debug

spring:
  profiles:
    include: oauth

  h2:
    console:
      enabled: true

#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://k5a101.p.ssafy.io:3306/whoyou?autoReconnect=true&useUnicode=true&characterEncoding=utf8mb4&serverTimezone=KST
    username: whoyou
    password: whoyou1admin!

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    showSql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties.hibernate:
#      hbm2ddl.auto: update
      format_sql: true

## security switch
#  security:
#    basic:
#      enabled: false
