server:
  port: 8085

spring:
  profiles:
    include: oauth

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://k5a101.p.ssafy.io:3306/whoyou?autoReconnect=true&useUnicode=true&characterEncoding=utf8mb4&serverTimezone=KST
    username: whoyou
    password: whoyou1admin!

  jpa:
    showSql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false

## security switch
#  security:
#    basic:
#      enabled: false

logging:
  level:
    com.status.backend: debug
